version: "2"
run:
  build-tags:
    - e2e
linters:
  default: none
  enable:
    - asciicheck
    - bidichk
    - bodyclose
    - depguard
    - durationcheck
    - errcheck
    - errname
    - errorlint
    - goconst
    - gocyclo
    - godot
    - govet
    - importas
    - ineffassign
    - misspell
    - nakedret
    - noctx
    - nolintlint
    - nosprintfhostport
    - predeclared
    - promlinter
    - staticcheck
    - unconvert
    - unused
    - wastedassign
    - whitespace
  settings:
    depguard:
      rules:
        main:
          deny:
            - pkg: io/ioutil
              desc: https://go.dev/doc/go1.16#ioutil
            - pkg: github.com/ghodss/yaml
              desc: use sigs.k8s.io/yaml instead
    govet:
      enable:
        - nilness # find tautologies / impossible conditions
    importas:
      alias:
        # Machine Controller
        - pkg: k8c.io/machine-controller/sdk/apis/(\w+)/(v[\w\d]+)
          alias: $1$2
        # Kubernetes
        - pkg: k8s.io/api/(\w+)/(v[\w\d]+)
          alias: $1$2
        - pkg: k8s.io/apimachinery/pkg/apis/meta/v1
          alias: metav1
        - pkg: k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1
          alias: apiextensionsv1
        - pkg: k8s.io/apimachinery/pkg/api/errors
          alias: apierrors
        - pkg: k8s.io/apimachinery/pkg/util/errors
          alias: kerrors
        # Controller Runtime
        - pkg: sigs.k8s.io/controller-runtime/pkg/client
          alias: ctrlruntimeclient
        # Other Kube APIs
        - pkg: go.anx.io/go-anxcloud/pkg/apis/(\w+)/(v[\w\d]+)
          alias: anx$1$2
        - pkg: github.com/tinkerbell/tink/api/(v[\w\d]+)
          alias: tink$1
        - pkg: kubevirt.io/api/(\w+)/(v[\w\d]+)
          alias: kubevirt$1$2
        - pkg: kubevirt.io/containerized-data-importer-api/pkg/apis/(\w+)/(v[\w\d]+)
          alias: cdi$1$2
      no-unaliased: true
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - path: (.+)\.go$
        text: func Convert_MachinesV1alpha1Machine_To_ClusterV1alpha1Machine should be ConvertMachinesV1alpha1MachineToClusterV1alpha1Machine
      - path: (.+)\.go$
        text: func Convert_MachineDeployment_ProviderConfig_To_ProviderSpec should be ConvertMachineDeploymentProviderConfigToProviderSpec
      - path: (.+)\.go$
        text: func Convert_MachineSet_ProviderConfig_To_ProviderSpec should be ConvertMachineSetProviderConfigToProviderSpec
      - path: (.+)\.go$
        text: func Convert_Machine_ProviderConfig_To_ProviderSpec should be ConvertMachineProviderConfigToProviderSpec
      - path: (.+)\.go$
        text: cyclomatic complexity [0-9]+ of func `\(\*provider\)\.Create` is high
      - path: (.+)\.go$
        text: cyclomatic complexity [0-9]+ of func `\(\*provider\)\.Validate` is high
      - path: (.+)\.go$
        text: cyclomatic complexity [0-9]+ of func `\(\*provider\)\.getConfig` is high
      - path: (.+)\.go$
        text: 'SA1019: s.server.IPv6 is deprecated'
    paths:
      - apis/machines
      - third_party$
      - builtin$
      - examples$
issues:
  max-same-issues: 0
formatters:
  enable:
    - gofmt
  exclusions:
    generated: lax
    paths:
      - apis/machines
      - third_party$
      - builtin$
      - examples$
