run:
  timeout: 20m
  build-tags:
    - e2e
linters:
  enable:
    - asciicheck
    - bidichk
    - bodyclose
    - depguard
    - durationcheck
    - errcheck
    - errname
    - errorlint
    - exportloopref
    - goconst
    - gocyclo
    - godot
    - gofmt
    - gosimple
    - govet
    - importas
    - ineffassign
    - misspell
    - nakedret
    - noctx
    - nolintlint
    - nosprintfhostport
    - predeclared
    - promlinter
    - revive
    - staticcheck
    - tenv
    - unconvert
    - unused
    - wastedassign
    - whitespace
  disable-all: true

linters-settings:
  depguard:
    rules:
      main:
        deny:
          - { pkg: io/ioutil, desc: https://go.dev/doc/go1.16#ioutil }
          - { pkg: github.com/ghodss/yaml, desc: use sigs.k8s.io/yaml instead }

  govet:
    enable:
      - nilness # find tautologies / impossible conditions

issues:
  exclude:
    - func Convert_MachinesV1alpha1Machine_To_ClusterV1alpha1Machine should be ConvertMachinesV1alpha1MachineToClusterV1alpha1Machine
    - func Convert_MachineDeployment_ProviderConfig_To_ProviderSpec should be ConvertMachineDeploymentProviderConfigToProviderSpec
    - func Convert_MachineSet_ProviderConfig_To_ProviderSpec should be ConvertMachineSetProviderConfigToProviderSpec
    - func Convert_Machine_ProviderConfig_To_ProviderSpec should be ConvertMachineProviderConfigToProviderSpec
    - 'cyclomatic complexity 33 of func `\(\*provider\)\.Create` is high'
    - "SA1019: s.server.IPv6 is deprecated"
  exclude-dirs:
    - pkg/machines
