run:
  deadline: 20m
  build-tags:
    - e2e
  skip-dirs:
    - pkg/client
    - pkg/machines

linters:
  enable:
    - golint
    - govet
    - gofmt
    - structcheck
    - varcheck
    - interfacer
    - unconvert
    - ineffassign
    - goconst
    - gocyclo
    - misspell
    - gosimple
    - unused
    - errcheck
  disable-all: true

issues:
  exclude:
  - should have comment or be unexported
  - should have comment \\(or a comment on this block\\) or be unexported
  - func Convert_MachinesV1alpha1Machine_To_ClusterV1alpha1Machine should be ConvertMachinesV1alpha1MachineToClusterV1alpha1Machine
  - func Convert_MachineDeployment_ProviderConfig_To_ProviderSpec should be ConvertMachineDeploymentProviderConfigToProviderSpec
  - func Convert_MachineSet_ProviderConfig_To_ProviderSpec should be ConvertMachineSetProviderConfigToProviderSpec
  - func Convert_Machine_ProviderConfig_To_ProviderSpec should be ConvertMachineProviderConfigToProviderSpec
  - 'counter\.Set is deprecated: Use NewConstMetric'
  - 'eviction\.go:221:4: the surrounding loop is unconditionally terminated'
  - 'cyclomatic complexity 31 of func `verifyMigrateUID` is high'
  - 'cyclomatic complexity 31 of func `main` is high'
