run:
  deadline: 20m
  build-tags:
    - e2e
  skip-dirs:
    - pkg/client
    - pkg/machines

linters:
  enable:
    - asciicheck
    - bidichk
    - bodyclose
    - deadcode
    - depguard
    - durationcheck
    - errcheck
    - errname
    - errorlint
    - exportloopref
    - goconst
    - gocyclo
    - godot
    - gofmt
    - gosimple
    - govet
    - importas
    - ineffassign
    - misspell
    - nakedret
    - noctx
    - nolintlint
    - nosprintfhostport
    - predeclared
    - promlinter
    - revive
    - staticcheck
    - structcheck
    - tenv
    - unconvert
    - unused
    - varcheck
    - wastedassign
    - whitespace
  disable-all: true

issues:
  exclude:
    - should have comment or be unexported
    - should have comment \\(or a comment on this block\\) or be unexported
    - func Convert_MachinesV1alpha1Machine_To_ClusterV1alpha1Machine should be ConvertMachinesV1alpha1MachineToClusterV1alpha1Machine
    - func Convert_MachineDeployment_ProviderConfig_To_ProviderSpec should be ConvertMachineDeploymentProviderConfigToProviderSpec
    - func Convert_MachineSet_ProviderConfig_To_ProviderSpec should be ConvertMachineSetProviderConfigToProviderSpec
    - func Convert_Machine_ProviderConfig_To_ProviderSpec should be ConvertMachineProviderConfigToProviderSpec
    - 'counter\.Set is deprecated: Use NewConstMetric'
    - 'eviction\.go:221:4: the surrounding loop is unconditionally terminated'
    - "cyclomatic complexity 31 of func `verifyMigrateUID` is high"
    - "cyclomatic complexity 31 of func `main` is high"
    - 'cyclomatic complexity 34 of func `\(\*provider\)\.getConfig` is high'
    - 'cyclomatic complexity 31 of func `\(\*provider\)\.Validate` is high'
    - 'cyclomatic complexity 31 of func `\(\*provider\)\.Create` is high'
    # SA1019: node.Spec.ConfigSource is deprecated: Previously used to specify the source of the node's configuration for the DynamicKubeletConfig feature.
    # This feature is removed from Kubelets as of 1.24 and will be fully removed in 1.26. +optional
    # We still support setting dynamic kubelet config feature in machine-controller. Hence, ignoring this error.
    # TODO: remove this once we remove support for the feature in 1.23
    - "SA1019: node.Spec.ConfigSource is deprecated"
