apiVersion: v1
kind: Namespace
metadata:
  name: minio
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: minio-pv
  namespace: minio
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minio-pv-claim
  namespace: minio
  labels:
    app: minio-storage-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: minio
  namespace: minio
spec:
  replicas: 3
  selector:
    matchLabels:
      app: minio
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: minio
    spec:
      containers:
        - name: minio
          image: minio/minio:RELEASE.2019-07-10T00-34-56Z
          args:
            - server
            - /data
          readinessProbe:
            httpGet:
              port: 9000
              path: /minio/health/ready
            periodSeconds: 20
          livenessProbe:
            httpGet:
              path: /minio/health/live
              port: 9000
            initialDelaySeconds: 120
            periodSeconds: 20
          env:
            - name: MINIO_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  key: ACCESS_KEY
                  name: minio
            - name: MINIO_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  key: SECRET_KEY
                  name: minio
          resources:
            requests:
              cpu: 25m
              memory: 50Mi
          ports:
            - containerPort: 9000
          volumeMounts:
            - name: storage
              mountPath: "/data"
        - name: bucket-creator
          image: minio/mc
          command:
            - /bin/sh
            - -c
          args:
            - |
              set -euo pipefail
              mc config host add local http://127.0.0.1:9000 ${MINIO_ACCESS_KEY} ${MINIO_SECRET_KEY}

              echo "Waiting until minio is running..."
              until mc ls local; do echo "Retrying..."; sleep 2; done

              echo "Creating all buckets"
              mc mb --ignore-existing local/terraform-kubeone
              mc mb --ignore-existing local/kubermatic-etcd-backups
              mc mb --ignore-existing local/terraform-machine-controller

              echo "Successfully created all buckets. Going to sleep."
              sleep 360000
          env:
            - name: MINIO_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  key: ACCESS_KEY
                  name: minio
            - name: MINIO_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  key: SECRET_KEY
                  name: minio
          resources:
            requests:
              cpu: 10m
              memory: 10Mi
      nodeSelector:
        kubevirt.io/schedulable: "true"
      volumes:
        - name: storage
          persistentVolumeClaim:
            claimName: minio-pv-claim
---
apiVersion: v1
kind: Service
metadata:
  name: minio
  namespace: minio
spec:
  type: ClusterIP
  ports:
    - port: 9000
      targetPort: 9000
      protocol: TCP
  selector:
    app: minio
---
apiVersion: v1
kind: Secret
metadata:
  name: minio
  namespace: minio
data:
  ACCESS_KEY: UE1JQzFITVhOQjJSNjdSTlBJWDg=
  SECRET_KEY: TmVtaVd4K3VZNzlyY0owaFhya3R6SGsxZG05YzBrODVXZXBidVNsSw==
