apiVersion: v1
kind: Secret
metadata:
  # If you change the namespace/name, you must also
  # adjust the rbac rules
  name: machine-controller-aws
  namespace: kube-system
type: Opaque
stringData:
  accessKeyId: << AWS_ACCESS_KEY_ID >
  secretAccessKey: << AWS_SECRET_ACCESS_KEY >>
---
apiVersion: "machine.k8s.io/v1alpha1"
kind: Machine
metadata:
  name: machine1
spec:
  providerConfig:
    sshPublicKeys:
      - "<< YOUR_PUBLIC_KEY >>"
    cloudProvider: "aws"
    cloudProviderSpec:
    # If empty, can be set via AWS_ACCESS_KEY_ID env var
      accessKeyId:
        secretKeyRef:
          namespace: kube-system
          name: machine-controller-aws
          key: accessKeyId
    # If empty, can be set via AWS_SECRET_ACCESS_KEY env var
      secretAccessKey:
        secretKeyRef:
          namespace: kube-system
          name: machine-controller-aws
          key: secretAccessKey
      region: "eu-central-1"
      availabilityZone: "eu-central-1a"
      vpcId: "vpc-819f62e9"
      subnetId: "subnet-2bff4f43"
      instanceType: "t2.micro"
      diskSize: 50
      diskType: "gp2"
      tags:
        "KubernetesCluster": "6qsm86c2d"
    # Can be 'ubuntu', 'coreos' or 'centos'
    operatingSystem: "coreos"
    operatingSystemSpec:
      disableAutoUpdate: true
  roles:
  - "Node"
  versions:
    kubelet: "v1.9.6"
    containerRuntime:
      name: "docker"
      version: "1.13"
