apiVersion: "machine.k8s.io/v1alpha1"
kind: Machine
metadata:
  name: machine1
spec:
  metadata:
    name: node1
  providerConfig:
    sshPublicKeys:
      - "<< YOUR_PUBLIC_KEY >>"
    cloudProvider: "hetzner"
    cloudProviderSpec:
      token: "<< HETZNER_API_TOKEN >>"
      serverType: "cx11"
      datacenter: ""
      location: "fsn1"
    operatingSystem: "ubuntu"
    operatingSystemSpec:
      distUpgradeOnBoot: false
  roles:
  - "Node"
  versions:
    kubelet: "1.9.2"
    containerRuntime:
      name: "cri-o"
