apiVersion: v1
kind: Secret
metadata:
  # If you change the namespace/name, you must also
  # adjust the rbac rules
  name: machine-controller-digitalocean
  namespace: kube-system
type: Opaque
stringData:
  token: << DIGITALOCEAN_TOKEN >>
---
apiVersion: "machine.k8s.io/v1alpha1"
kind: Machine
metadata:
  name: machine1
spec:
  providerConfig:
    sshPublicKeys:
      - "<< YOUR_PUBLIC_KEY >>"
    cloudProvider: "digitalocean"
    cloudProviderSpec:
    # If empty, can be set via DO_TOKEN env var
      token:
        secretKeyRef:
          namespace: kube-system
          name: machine-controller-digitalocean
          key: token
      region: fra1
      size: 2gb
      backups: false
      ipv6: false
      private_networking: true
      # Monitoring must be turned off for CoreOS Container Linux
      monitoring: false
      tags:
        - "machine-controller"
    # Can be 'ubuntu', 'coreos' or 'centos'
    operatingSystem: "coreos"
    operatingSystemSpec:
      disableAutoUpdate: true
  roles:
  - "Node"
  versions:
    kubelet: "v1.9.6"
    containerRuntime:
      name: "docker"
      version: "1.13"
