apiVersion: "machine.k8s.io/v1alpha1"
kind: Machine
metadata:
  name: machine1
spec:
  metadata:
    name: node1
    labels:
      foo: "bar"
  providerConfig:
    sshPublicKeys:
      - "<< YOUR_PUBLIC_KEY >>"
    cloudProvider: "openstack"
    cloudProviderSpec:
      identityEndpoint: "<< YOUR_OS_AUTH_URL >>"
      username: "<< YOUR_OS_USERNAME >>"
      password: "<< YOUR_OS_PASSWORD >>"
      domainName: "<< YOUR_OS_DOMAIN >>"
      tenantName: "<< YOUR_OS_TENANT >>"
      image: "Ubuntu 16.04 amd64"
      flavor: "m1.small"
      securityGroups:
        - "external-ssh"
      # The machine won't get a floating ip if you leave this empty
      floatingIpPool: "ext-net"
      # Only required if there is more than one AZ to choose from
      availabilityZone: ""
      # Only required if there is more than one region to choose from
      region: ""
      # Only required if there is more than one network available
      network: ""
      # Only required if the network has more than one subnet
      subnet: ""
    operatingSystem: "ubuntu"
    operatingSystemSpec:
      distUpgradeOnBoot: true
  roles:
  - "Node"
  versions:
    kubelet: "v1.8.5" # Kubelet wrapper image tag
    containerRuntime:
      # If you are using Ubuntu, you may choose 'cri-o' instead
      name: "docker"
      # Only has an effect on Ubuntu, check pkg/userdata/ubuntu/docker.go for available versions
      version: "1.13"
