apiVersion: v1
kind: Secret
metadata:
  # If you change the namespace/name, you must also
  # adjust the rbac rules
  name: machine-controller-hetzner
  namespace: kube-system
type: Opaque
stringData:
  token: << HETZNER_TOKEN >>
---
apiVersion: "machine.k8s.io/v1alpha1"
kind: Machine
metadata:
  name: machine1
spec:
  metadata:
    name: node1
  providerConfig:
    sshPublicKeys:
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDHBgwMTqA8AFS3UhHUXkYZ7pkWnGdFqB18uz/5Ai0mT0qgN1aY4kiGruI2uDgiTu1s3ypBrPr8Zg8Vqurrvr4p+BM0lfWQyslG+Q/UecYy0g6qAs9NriT2iWLlCUb9oFJ8Um30Lmj5I00DjnxjEDAY+nTijJvOK0fd+0HYwKmAWYLEDrGNXxW1EVoKmYoO0+Xp3p+K2xJ/7KIiKMyLVcYs5qbNHkTgywjsIW7DLhEkLIRXeubjwV1YHgsxg+8v4jCHYCrabRtG/gMLCQ7+CFST6IxwTKQB1u7U+2zjRpafOLJf/DHCGiQavqVDEZ36xYYvs67hlf3Fs3fwK4VJ0cuh Alvaro Aleman <alv2412@gmail.com>
    cloudProvider: "hetzner"
    cloudProviderSpec:
      token:
        secretKeyRef:
          namespace: kube-system
          name: machine-controller-hetzner
          key: token
      serverType: "cx11"
      datacenter: ""
      location: "fsn1"
    operatingSystem: "el"
  roles:
  - "Node"
  versions:
    kubelet: "1.9.2"
    containerRuntime:
      name: "docker"
      version: "1.13"
